"""Quality control utilities for Copernicus Sentinel-1 and Sentinel-2 satellite data.

This module provides functions for quality assessment and masking of satellite imagery:
- Sentinel-2: Cloud masking using the Scene Classification Layer (SCL)
- Sentinel-1: Invalid pixel detection, border noise detection, orbit type extraction
- Shared quality_gate() verdict function for both S1 and S2 reports
"""

import tempfile
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path
from typing import Any, Dict, Optional

import numpy as np
import rasterio

from .utils import extract_s2_safe_structure


def extract_cloud_mask(zip_file_path: Path) -> Optional[np.ndarray]:
    """Extract cloud mask from Sentinel-2 Scene Classification Layer (SCL).

    WHAT IS THE SCL BAND:
    The Scene Classification Layer (SCL) is a quality band included with Sentinel-2
    Level-2A products. It classifies each pixel into categories like cloud, shadow,
    vegetation, water, etc. This is generated by the Sen2Cor atmospheric correction
    algorithm.

    WHY CLOUD MASKING MATTERS:
    Clouds obscure the ground and make optical imagery unusable for analysis.
    Cloud masking allows you to:
    - Identify which pixels contain valid ground observations
    - Exclude cloudy pixels from analysis
    - Find the clearest images in a time series
    - Create cloud-free composites by combining multiple images

    SCL CLASSIFICATION VALUES:
    The SCL band uses integer values to classify each pixel:
    - 0 = No Data (missing or invalid)
    - 1 = Saturated or defective pixel
    - 2 = Dark area (very low reflectance, topographic shadow)
    - 3 = Cloud shadow
    - 4 = Vegetation (CLEAR - keep this)
    - 5 = Not vegetated (bare soil, rock) (CLEAR - keep this)
    - 6 = Water (CLEAR - keep this)
    - 7 = Unclassified
    - 8 = Cloud medium probability (MASK OUT)
    - 9 = Cloud high probability (MASK OUT)
    - 10 = Thin cirrus (high altitude ice clouds) (MASK OUT)
    - 11 = Snow or ice (usually MASK OUT, depends on application)

    MASKING STRATEGY:
    We create a binary mask where:
    - 1 (True) = Clear pixel, safe to use (classes 4, 5, 6)
    - 0 (False) = Problematic pixel, should be masked (clouds, shadows, etc.)

    Args:
        zip_file_path: Path to Sentinel-2 Level-2A ZIP file
                      Note: Level-1C products don't have SCL band!
                      Example: S2A_MSIL2A_20220101T123456_..._.zip

    Returns:
        Binary mask array where:
        - 1 = Clear pixel (vegetation, bare soil, water)
        - 0 = Masked pixel (cloud, shadow, snow, etc.)
        Shape: (height, width) matching the 20m resolution bands
        Returns None if extraction fails or SCL band not found
    """
    try:
        with extract_s2_safe_structure(zip_file_path) as (safe_dir, granule_dir):
            # Check if this is a Level-2A product (has SCL band)
            if "MSIL1C" in safe_dir.name:
                print(
                    f"Warning: {zip_file_path.name} is Level-1C (no SCL band). "
                    "Cloud masking requires Level-2A products."
                )
                return None

            # SCL band is in IMG_DATA/R20m/ subdirectory (20m resolution)
            img_dir_20m = granule_dir / "IMG_DATA" / "R20m"
            if not img_dir_20m.exists():
                # Try alternative structure (older products)
                img_dir_20m = granule_dir / "IMG_DATA"

            # Find SCL band file
            scl_patterns = [
                "*_SCL_20m.jp2",  # Standard pattern
                "*_SCL.jp2",  # Alternative pattern
                "*SCL*.jp2",  # Fallback pattern
            ]

            scl_file = None
            for pattern in scl_patterns:
                scl_matches = list(img_dir_20m.glob(pattern))
                if scl_matches:
                    scl_file = scl_matches[0]
                    break

            if scl_file is None:
                print(f"SCL band not found in {zip_file_path.name}")
                print(f"Available files: {list(img_dir_20m.glob('*.jp2'))}")
                return None

            # Read SCL band
            with rasterio.open(scl_file) as src:
                scl_data = src.read(1)  # Read first (and only) band

            # Create binary mask based on SCL classification
            # Clear pixels: vegetation (4), not vegetated (5), water (6)
            clear_classes = [4, 5, 6]

            # Initialize mask as all zeros (all masked)
            mask = np.zeros_like(scl_data, dtype=np.uint8)

            # Set clear pixels to 1
            for clear_class in clear_classes:
                mask[scl_data == clear_class] = 1

            # Calculate cloud coverage statistics
            total_pixels = mask.size
            clear_pixels = mask.sum()
            cloud_coverage = (1 - clear_pixels / total_pixels) * 100

            print(f"Cloud coverage: {cloud_coverage:.1f}% (based on SCL classification)")

            return mask

    except Exception as e:
        print(f"Error extracting cloud mask from {zip_file_path.name}: {e}")
        import traceback

        traceback.print_exc()
        return None


def apply_cloud_mask_to_image(
    image_array: np.ndarray, cloud_mask: np.ndarray, fill_value: float = 0.0
) -> np.ndarray:
    """Apply cloud mask to an image array.

    This function sets cloudy pixels to a fill value (typically 0 or NaN).

    Args:
        image_array: Image array to mask, shape (H, W) or (H, W, C)
        cloud_mask: Binary mask where 1=clear, 0=cloudy, shape (H, W)
        fill_value: Value to use for masked pixels (0.0 for black, np.nan for NaN)

    Returns:
        Masked image array with same shape as input
    """
    # Create a copy to avoid modifying original
    masked_image = image_array.copy()

    # Handle different array dimensions
    if image_array.ndim == 2:
        # Single band image (H, W)
        masked_image[cloud_mask == 0] = fill_value
    elif image_array.ndim == 3:
        # Multi-band image (H, W, C)
        # Broadcast mask across all channels
        masked_image[cloud_mask == 0, :] = fill_value
    else:
        raise ValueError(f"Unsupported image dimensions: {image_array.ndim}")

    return masked_image


# ---------------------------------------------------------------------------
# Sentinel-1 SAR quality assessment
# ---------------------------------------------------------------------------


def _count_invalid_pixels(band_data: np.ndarray) -> float:
    """Count the percentage of invalid pixels in a SAR band.

    Invalid pixels are: zero (no data received), NaN, or extreme outliers
    (values beyond ±5 standard deviations from the mean of valid pixels).

    Args:
        band_data: 2-D array of SAR backscatter values (linear scale).

    Returns:
        Percentage of invalid pixels (0.0–100.0).
    """
    total = band_data.size
    if total == 0:
        return 100.0

    # Zeros and NaNs
    invalid_mask = np.isnan(band_data) | np.isinf(band_data) | (band_data == 0)

    # Outlier detection on the valid subset
    valid = band_data[~invalid_mask]
    if valid.size > 0:
        mean = valid.mean()
        std = valid.std()
        if std > 0:
            outlier_mask = np.abs(band_data - mean) > 5 * std
            invalid_mask = invalid_mask | outlier_mask

    return float(np.sum(invalid_mask) / total * 100.0)


def _detect_border_noise(
    band_data: np.ndarray,
    edge_pixels: int = 50,
    zero_threshold: float = 0.9,
) -> bool:
    """Detect border noise in a SAR image.

    S1 GRD products (especially pre-March 2018) have strips of noisy/zero
    pixels along the swath edges.  We scan the first and last N columns/rows
    and flag the tile if any edge is predominantly zero.

    Args:
        band_data: 2-D array of SAR backscatter values.
        edge_pixels: Number of rows/columns to inspect at each edge.
        zero_threshold: Fraction of near-zero pixels that triggers the flag.

    Returns:
        True if border noise is detected on any edge.
    """
    h, w = band_data.shape
    edge_pixels = min(edge_pixels, h // 4, w // 4)  # Don't exceed quarter of image
    if edge_pixels < 1:
        return False

    near_zero = 1e-10  # Threshold for "near-zero" in linear scale

    edges = [
        band_data[:edge_pixels, :],  # top rows
        band_data[-edge_pixels:, :],  # bottom rows
        band_data[:, :edge_pixels],  # left columns
        band_data[:, -edge_pixels:],  # right columns
    ]

    for edge in edges:
        zero_frac = np.sum(np.abs(edge) < near_zero) / edge.size
        if zero_frac >= zero_threshold:
            return True

    return False


def _extract_orbit_type(safe_dir: Path) -> Optional[str]:
    """Extract orbit type (precise / restituted) from manifest.safe.

    The manifest.safe XML inside the .SAFE directory contains a
    ``<s1sarl1:orbitReference>`` element whose child
    ``<safe:extension><s1sarl1:orbitProperties><s1sarl1:pass>`` or
    ``<safe:orbitNumber>`` attributes indicate the orbit file used.
    The key field is ``<s1sarl1:extension><s1sarl1:orbitProperties>``
    with ``type`` attribute, but the most reliable indicator is the
    ``metadataObject`` with ID ``measurementOrbitReference`` whose
    ``xmlData`` contains the orbit file name.  Orbit file names
    starting with ``AUX_POEORB`` = precise, ``AUX_RESORB`` = restituted.

    Falls back to searching for the raw strings in the XML text.

    Args:
        safe_dir: Path to the extracted .SAFE directory.

    Returns:
        ``"precise"``, ``"restituted"``, or ``None`` if undetermined.
    """
    manifest = safe_dir / "manifest.safe"
    if not manifest.exists():
        return None

    try:
        content = manifest.read_text(errors="replace")

        # Fast string search — orbit file references are embedded in the XML
        if "AUX_POEORB" in content:
            return "precise"
        if "AUX_RESORB" in content:
            return "restituted"

        # Fallback: try XML parsing for less common layouts
        tree = ET.parse(manifest)
        root = tree.getroot()
        xml_str = ET.tostring(root, encoding="unicode")
        if "AUX_POEORB" in xml_str:
            return "precise"
        if "AUX_RESORB" in xml_str:
            return "restituted"

    except Exception as e:
        print(f"Warning: could not parse orbit type from manifest.safe: {e}")

    return None


def assess_s1_quality(
    zip_file_path: Path,
    edge_pixels: int = 50,
) -> Optional[Dict[str, Any]]:
    """Assess quality of a Sentinel-1 GRD product.

    Opens the ZIP, reads VV/VH TIFF bands, and computes:
    - invalid_pixel_pct: percentage of zero / NaN / outlier pixels
    - border_noise_detected: boolean flag for swath-edge noise
    - orbit_type: "precise" or "restituted" (from manifest.safe)
    - usable_pct: 100 - invalid_pixel_pct

    Args:
        zip_file_path: Path to a Sentinel-1 ZIP file (GRD product).
        edge_pixels: Number of edge rows/cols to scan for border noise.

    Returns:
        Quality report dict, or None on failure::

            {
                "invalid_pixel_pct": 3.2,
                "border_noise_detected": True,
                "orbit_type": "precise",
                "usable_pct": 96.8,
            }
    """
    try:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)

            with zipfile.ZipFile(zip_file_path, "r") as zf:
                zf.extractall(tmp_path)

            safe_dirs = list(tmp_path.glob("*.SAFE"))
            if not safe_dirs:
                print(f"No .SAFE directory in {zip_file_path.name}")
                return None
            safe_dir = safe_dirs[0]

            # --- Read polarization TIFFs ---
            measurement_dir = safe_dir / "measurement"
            if not measurement_dir.exists():
                print(f"No measurement/ directory in {zip_file_path.name}")
                return None

            tiff_files = list(measurement_dir.glob("*.tiff"))
            if not tiff_files:
                print(f"No TIFF files in {zip_file_path.name}")
                return None

            # Aggregate invalid-pixel stats across all polarisation bands
            all_invalid_pcts: list[float] = []
            border_noise = False

            for tiff in tiff_files:
                with rasterio.open(tiff) as src:
                    data = src.read(1).astype(np.float32)

                all_invalid_pcts.append(_count_invalid_pixels(data))

                if not border_noise:
                    border_noise = _detect_border_noise(data, edge_pixels=edge_pixels)

            invalid_pct = float(np.mean(all_invalid_pcts)) if all_invalid_pcts else 100.0

            # --- Orbit type ---
            orbit_type = _extract_orbit_type(safe_dir)

            return {
                "invalid_pixel_pct": round(invalid_pct, 2),
                "border_noise_detected": border_noise,
                "orbit_type": orbit_type,
                "usable_pct": round(100.0 - invalid_pct, 2),
            }

    except Exception as e:
        print(f"Error assessing S1 quality for {zip_file_path.name}: {e}")
        import traceback

        traceback.print_exc()
        return None


# ---------------------------------------------------------------------------
# Shared quality gate (works for both S1 and S2 reports)
# ---------------------------------------------------------------------------


def quality_gate(
    usable_pct: float,
    threshold: float = 90.0,
    marginal_offset: float = 10.0,
) -> str:
    """Return a quality verdict based on usable pixel percentage.

    The same function is used for both S2 (cloud-free %) and S1 (valid pixel %).

    Verdicts:
    - ``"ACCEPT"``   — usable_pct >= threshold
    - ``"MARGINAL"`` — usable_pct >= threshold - marginal_offset
    - ``"REJECT"``   — usable_pct < threshold - marginal_offset

    Args:
        usable_pct: Percentage of usable pixels (0–100).
        threshold: Minimum usable % to fully accept (default 90).
        marginal_offset: Width of the marginal band below threshold (default 10).

    Returns:
        One of ``"ACCEPT"``, ``"MARGINAL"``, ``"REJECT"``.
    """
    if usable_pct >= threshold:
        return "ACCEPT"
    if usable_pct >= threshold - marginal_offset:
        return "MARGINAL"
    return "REJECT"
